name: deploy
on:
  push:
    branches: main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          load: true
          tags: pretzel:latest

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Save image
        run: docker save pretzel:latest | gzip | ssh ${{ secrets.SSH_USER}}@${{secrets.SSH_HOST}} docker load

      - name: Run redeploy script
        run: ssh ${{ secrets.SSH_USER}}@${{secrets.SSH_HOST}} ./redeploy.sh pretzel
